### ISSUE TITLE
Unable to install via composer "[UnexpectedValueException] Could not parse version constraint <=2.*: Invalid version string "2.*"

### ISSUE THREAD

**Issue by rajeev1985sh** [joni-jones/yii2-wschat#12]
I am using yii2 2.0.5 version and when try to install your extension via composer got following error.

nearyou@nearyou-desktop:/var/www/eventnew$ composer require --prefer-dist joni-jones/yii2-wschat "*"
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)

  [UnexpectedValueException]  
  Could not parse version constraint <=2._: Invalid version string "2._"  

require [--dev] [--prefer-source] [--prefer-dist] [--no-progress] [--no-update] [--update-no-dev] [--update-with-dependencies] [--ignore-platform-reqs] [--sort-packages] [packages1] ... [packagesN]

nearyou@nearyou-desktop:/var/www/eventnew$ composer update
Loading composer repositories with package information
Updating dependencies (including require-dev)

  [UnexpectedValueException]  
  Could not parse version constraint <=2._: Invalid version string "2._"  

update [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--lock] [--no-plugins] [--no-custom-installers] [--no-autoloader] [--no-scripts] [--no-progress] [--with-dependencies] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [packages1] ... [packagesN]

Can please help me and figure it out what mistake i am making, thanks.

**Comment by YevSent** [comment]
@coder-man, please, add your `composer.json` file, because I can't reproduce your error(tried `stable` and `dev` stabilities).

**Comment by rajeev1985sh** [comment]
{
    "name": "yiisoft/yii2-app-advanced",
    "description": "Yii 2 Advanced Project Template",
    "keywords": ["yii2", "framework", "advanced", "project template"],
    "homepage": "http://www.yiiframework.com/",
    "type": "project",
    "license": "BSD-3-Clause",
    "support": {
        "issues": "https://github.com/yiisoft/yii2/issues?state=open",
        "forum": "http://www.yiiframework.com/forum/",
        "wiki": "http://www.yiiframework.com/wiki/",
        "irc": "irc://irc.freenode.net/yii",
        "source": "https://github.com/yiisoft/yii2"
    },
    "minimum-stability": "stable",
    "require": {
        "php": ">=5.4.0",
        "yiisoft/yii2": ">=2.0.4",
        "yiisoft/yii2-bootstrap": "_",
        "yiisoft/yii2-swiftmailer": "_",
        "oncesk/yii-node-socket" : "2.0.4",
        "dmstr/yii2-adminlte-asset": "2._",
         "yiisoft/yii2-jui": "2.0._@dev",
         "kartik-v/yii2-widgets": "_",
        "fxp/composer-asset-plugin": "~1.0@dev",
        "sintret/yii2-chat-adminlte": "dev-master",  
        "joni-jones/yii2-wschat": "_"
    },
    "require-dev": {
        "yiisoft/yii2-codeception": "_",
        "yiisoft/yii2-debug": "_",
        "yiisoft/yii2-gii": "_",
        "yiisoft/yii2-faker": "_"
    },
    "config": {
        "process-timeout": 1800
    },
    "extra": {
        "asset-installer-paths": {
            "npm-asset-library": "vendor/npm",
            "bower-asset-library": "vendor/bower"
        }
    }
}

**Comment by rajeev1985sh** [comment]
Please guide me to what composer command with options, i need to run for proper installation of you extension. Thanks

**Comment by YevSent** [comment]
Your problem not related to chat package, please recheck `"dmstr/yii2-adminlte-asset": "2.",` this line is  incorrect. Should be `2.*` instead `2.`.

**Comment by rajeev1985sh** [comment]
Ok, thanks for pointing out the issue, its "2.*" in composer file may copy paste issue, still having the same issue, well thanks its not related to your package, will try with fresh installation Again thanks for your help.

**Comment by YevSent** [comment]
You have another issues in the composer file: `"yiisoft/yii2-codeception": ""` should be `"yiisoft/yii2-codeception": "*"` and many others.
