### ISSUE TITLE
Class 'ChatWidget' not found

### ISSUE THREAD

**Issue by Tatiana96** [joni-jones/yii2-wschat#15]
Здравствуйте! Помогите новичку, пожалуйста. Все сделала строго по Вашей инструкции, а в итоге получаю 
![2016-01-17_234434](https://cloud.githubusercontent.com/assets/7083603/12379119/28792150-bd75-11e5-98fd-ba69ae6ef8e7.jpg)
PHP Fatal Error – yii\base\ErrorException
Class 'ChatWidget' not found. 
Все пути уже проверила во всех файлах, вроде все правильно.

**Comment by YevSent** [comment]
Добрый вечер, а неймспейс в файле вьюшки у Вас правильно указан для ChatWidget?

**Comment by Tatiana96** [comment]
Спасибо большое за ответ!

Если я правильно понимаю, namespace должен быть таким?
![namespace](https://cloud.githubusercontent.com/assets/7083603/12379858/fc018666-bd84-11e5-9a71-b01ee3a33e4b.jpg)

**Comment by YevSent** [comment]
Почти, `use jones\wschat\ChatWidget`

**Comment by Tatiana96** [comment]
Огромное спасибо за помощь!

И еще вопрос, если можно:
чат не реагирует на действия, а в консоли вот такие ошибки:
![errors](https://cloud.githubusercontent.com/assets/7083603/12389784/e4370e48-bdfc-11e5-9ab5-171e50f76457.jpg)
![errors2](https://cloud.githubusercontent.com/assets/7083603/12389850/528ed6e6-bdfd-11e5-9950-96b367685dab.jpg)
Запускаю в Mozilla Firefox. Но я полагаю, проблема не в этом.
Подскажите, пожалуйста, как можно решить эту проблему?

**Comment by YevSent** [comment]
Судя по всему у вас не подрузились js ассеты, а у Вас https://packagist.org/packages/fxp/composer-asset-plugin установлен глобально или для проекта?

**Comment by Tatiana96** [comment]
Переустановила плагин и обновила проект. Помогло. Спасибо большое!

Появилась проблема с добавлением юзера. Пишет, что чат не доступен.
![default](https://cloud.githubusercontent.com/assets/7083603/12399164/17bfe234-be3a-11e5-9e5e-fbbe45790a82.jpg)

Настроила логи, как Вы указали. И в файле console.php, и в файле web.php.
![default](https://cloud.githubusercontent.com/assets/7083603/12399191/4dce0b62-be3a-11e5-9fef-75a6bf216196.jpg)

Но ошибок никаких не выводит. Только сообщения о начале сессий.
![default](https://cloud.githubusercontent.com/assets/7083603/12399211/674fe826-be3a-11e5-8ef6-179e96a46757.jpg)

Подскажите, пожалуйста, что может быть неправильно?

**Comment by YevSent** [comment]
Попробуйте почистить куки

**Comment by Tatiana96** [comment]
Появилась ошибка соединения.
![logs](https://cloud.githubusercontent.com/assets/7083603/12400261/cc823dc4-be40-11e5-873a-d3ba7b1a014e.jpg)

Веб-сокеты неправильно работают?

**Comment by YevSent** [comment]
Я не вижу ошибки, наоборот, логи говорят что соединение установлено.

**Comment by Tatiana96** [comment]
Да, с соединением все хорошо. Я сначала неправильно поняла проблему.
С базой данных проблема:
не может подключиться, хотя сама база есть, и коллекция "history" тоже
![default](https://cloud.githubusercontent.com/assets/7083603/12401080/e9b85342-be45-11e5-96b3-0df34b7f987b.jpg)
![2](https://cloud.githubusercontent.com/assets/7083603/12401084/f02b6192-be45-11e5-985d-db14de0c17be.jpg)

**Comment by YevSent** [comment]
так у Вас авторизация к бд не проходит

**Comment by Tatiana96** [comment]
Разобралась, настроила, все работает)
Извините за такие глупые вопросы)
Спасибо огромное, Вы мне очень помогли :)

**Comment by YevSent** [comment]
Всегда пожалуйста
