### ISSUE TITLE
Дисконнект через какое то время.

### ISSUE THREAD

**Issue by vari-arti** [joni-jones/yii2-wschat#16]
Подключил, все работает, но через некоторое время происходит дисконнект, в логах пусто, хотя если писать сообщения до дисконнекта, то логирование происходит.
Использую OpenServer, может ли трабла быть в этом?

**Comment by YevSent** [comment]
На OpenServer не тестировал, тут подсказать не могу. Посмотрите в логах самого OpenServer, может там что-то есть

**Comment by philippfrenzel** [comment]
Sorry my russian is terrible;) is this an important information? Thanks;)

**Comment by YevSent** [comment]
@philippfrenzel if you aren't have troubles with disconnect, I think you can skip this issue.

**Comment by vari-arti** [comment]
Разобрался, не верно настроил логи, когда сделал как описано в доках, все заработало, в любом случае спасибо.
Там есть такая трабла, что на OpenServer происходил дисконнект из за MySql, он там так настроен у меня, через mongodb все заработало как нужно.

**Comment by YevSent** [comment]
Будут вопросы обращайтесь
