### ISSUE TITLE
Не получается запустить.

### ISSUE THREAD

**Issue by hrupin** [joni-jones/yii2-wschat#17]
Поставил по инструкции, при запуске сервера сообщение не выходит
`php ./yii server/run`
только мигает курсор 
![2016-03-13 17 25 14](https://cloud.githubusercontent.com/assets/8831621/13729253/b9a6051a-e941-11e5-8bea-7a5fe95ee644.png)

сам чат выдает ошибку и не работает. В консоле пусто и логах тоже

![2016-03-13 17 27 00](https://cloud.githubusercontent.com/assets/8831621/13729261/f4d8d194-e941-11e5-8142-4cb63d4dbd9e.png)
![2016-03-13 17 28 33](https://cloud.githubusercontent.com/assets/8831621/13729266/051ba5c2-e942-11e5-8be2-576cda35b3f0.png)

Что я делаю не так? А то уже второй день ломаю голову(((((

**Comment by hrupin** [comment]
настройки логов и базы

`'log' => [

```
        'traceLevel' => YII_DEBUG ? 3 : 0,

        'flushInterval' => 1,

        'targets' => [

            [

                'class' => 'yii\log\FileTarget',

                'levels' => ['error', 'warning', 'info'],

                'logVars' => [],

                'exportInterval' => 1

            ],

        ],

    ],

    'db' => require(__DIR__ . '/db.php'),

    'mongodb' => [

        'class' => '\yii\mongodb\Connection',

        'dsn' => 'mongodb://localhost:27017/testdemo'

    ]`
```

**Comment by YevSent** [comment]
А в консоли браузера нет ошибок? Еще странно, что у Вас в логах нет сообщений о инициализации чата.

**Comment by hrupin** [comment]
Нет, в консоли браузера тишина. Только если после выдачи ошибки, пытаешься отправить сообщение. Выдает ошибку 
![2016-03-13 23 56 18](https://cloud.githubusercontent.com/assets/8831621/13731344/71f65310-e977-11e5-9c3b-c45368da017e.png)

а если не запускать команду server/run

![2016-03-13 23 54 02](https://cloud.githubusercontent.com/assets/8831621/13731349/818c6d5a-e977-11e5-8cee-e82212562974.png)

**Comment by YevSent** [comment]
Вы в лог панели видите только логи текущего запроса к site/index. Откройте runtime/logs/app.log и там должны быть логи для чата

**Comment by hrupin** [comment]
в файле runtime/logs/app.log:

2016-03-13 20:53:47 [127.0.0.1][-][htn9qihtl3neegltdt6mc7o6n2][info][yii\web\Session::open] Session started
    in /home/sandro/SERVER/www/site/site/views/layouts/main.php:42
    in /home/sandro/SERVER/www/site/site/controllers/SiteController.php:52
2016-03-13 20:55:43 [127.0.0.1][-][htn9qihtl3neegltdt6mc7o6n2][info][yii\web\Session::open] Session started
    in /home/sandro/SERVER/www/site/site/views/layouts/main.php:42
    in /home/sandro/SERVER/www/site/site/controllers/SiteController.php:52
2016-03-13 20:55:49 [127.0.0.1][-][htn9qihtl3neegltdt6mc7o6n2][info][yii\web\Session::open] Session started
    in /home/sandro/SERVER/www/site/site/views/layouts/main.php:42
    in /home/sandro/SERVER/www/site/site/controllers/SiteController.php:52
2016-03-13 20:55:58 [127.0.0.1][-][htn9qihtl3neegltdt6mc7o6n2][info][yii\web\Session::open] Session started
    in /home/sandro/SERVER/www/site/site/views/layouts/main.php:42
    in /home/sandro/SERVER/www/site/site/controllers/SiteController.php:52

Больше нет ничего

**Comment by YevSent** [comment]
У Вас нет в логах коннекта к mongo и сообщений что сессия для пользователя создана. А попап создания пользователя появляется? и какую версию используете?

**Comment by hrupin** [comment]
Да, появляется. Но когда ввожу имя и отправляю, пишет conection refused. Потом обновляю окно не появляется попап, только ошибка conection refused

yii2 basic

mongod --version
db version v2.6.11

**Comment by YevSent** [comment]
Я про версию пакета чат виджета. Судя по описанию у Вас не создается пользовательская версия для чата. И даже нет коннекта к монго, иначе в логах это было б. Коллекция для чата доступна из монго консоли?

**Comment by hrupin** [comment]
"joni-jones/yii2-wschat": "1.0.0-beta"

я в монго не силен(((, а как проверить?

**Comment by YevSent** [comment]
https://docs.mongodb.org/manual/mongo/#working-with-the-mongo-shell. Виджет также поддерживает mysql и postgresql

**Comment by hrupin** [comment]
А как его переключить на mySQL?

**Comment by YevSent** [comment]
Указываете как обычное подключение к ДБ. Монго компонент нужно убрать в этом случае.

**Comment by hrupin** [comment]
То есть просто удаляю:

'mongodb' => [

```
    'class' => '\yii\mongodb\Connection',

    'dsn' => 'mongodb://localhost:27017/testdemo'

]`
```

я правильно понял?

**Comment by YevSent** [comment]
Если Вы хотите использовать mysql или postgres вместо mongodb, то да удаляете монго компонент и указываете нужную бд. В ридми указано где можно взять альтеры для бд.

**Comment by hrupin** [comment]
Сейчас все заработало, значит я скорее всего намудрил с монгодб. Спасибо большое.
