### ISSUE TITLE
yiisoft/yii2-mongodb 2.0.5 requires ext-mongo >=1.5.0 -> the requested PHP extension mongo is missing from your system.

### ISSUE THREAD

**Issue by ak868308** [joni-jones/yii2-wschat#19]
This error annoying me 
why I am facing such problem. Is it database issue I am using MySql 
![com_3](https://cloud.githubusercontent.com/assets/7982249/16234663/ae7632a8-37ef-11e6-9ae0-c1461f52bb11.png)

**Comment by YevSent** [comment]
This issue related to mongo extension for Yii framework and described in the readme file. New version of mongo db already implemented, so I will update chat extension ASAP.

**Comment by YevSent** [comment]
Fixed in https://github.com/joni-jones/yii2-wschat/commit/419f71b0560f89b7ad2c7f3d7132114f8a31868a, but the `dev` stability is still required.

**Comment by toir427** [comment]
Great. thanks @joni-jones
