### ISSUE TITLE
Packagist issue

### ISSUE THREAD

**Issue by antonkomarev** [joni-jones/yii2-wschat#2]
Hello, I can't find your package on Packagist:
https://packagist.org/packages/joni-jones/

Composer error:

```
 Problem 1
    - The requested package joni-jones/yii2-wschat could not be found in any version, there may be a typo in the package name.
```

**Comment by YevSent** [comment]
Hello, I've added chat repo to packagist.org

**Comment by antonkomarev** [comment]
Thank you. Because I were needed to publish you package there too to make it work via composer.
