### ISSUE TITLE
other db engine?

### ISSUE THREAD

**Issue by philippfrenzel** [joni-jones/yii2-wschat#5]
Hi, 

do you plan to support other db engines too?

Thanks Philipp

**Comment by YevSent** [comment]
Hi, @philippfrenzel. In the near future I've plan to add abstract model for history storing and developers  will can specify needed db driver in the application config.

**Comment by philippfrenzel** [comment]
Hi, this World be Great as I would love this component on MySQL or mssql - let me know if I can help?

**Comment by YevSent** [comment]
Ok, sure. I will try to implement new storage interaction at this weekend.

**Comment by YevSent** [comment]
New db storage was added.
