### ISSUE TITLE
Don't install

### ISSUE THREAD

**Issue by QuinLena15** [joni-jones/yii2-wschat#9]
Hello! I have problem.
![screenshot_4](https://cloud.githubusercontent.com/assets/10464561/7936802/7ef2170c-0944-11e5-93ea-9ac5c19ec457.png)

**Comment by YevSent** [comment]
Which `stability` version you are specified in composer.json?

**Comment by QuinLena15** [comment]
The file composer.json added line "joni-jones / yii2-wschat": "dev-master". After you execute the command php composer.phar update. It generates an error , which is screenshot

**Comment by YevSent** [comment]
I understand this. My question is about `stability` option in your composer file for all packages.

**Comment by QuinLena15** [comment]
"minimum-stability": "stable".

**Comment by YevSent** [comment]
Can you attach your `composer.json`?

**Comment by QuinLena15** [comment]
{
    "name": "name",
    "description": "description",
    "keywords": ["yii2", "name"],
    "homepage": "http://namesite.com",
    "type": "project",
    "license": "BSD-3-Clause",

```
"minimum-stability": "stable",
"require": {
    "php": ">=5.4.0",
    "yiisoft/yii2": "*",
    "yiisoft/yii2-bootstrap": "*",
    "yiisoft/yii2-swiftmailer": "*",
    "developeruz/yii2-db-rbac": "dev-master",
     "nodge/yii2-eauth": "~2.0",
    "2amigos/yii2-tinymce-widget": "~1.1",
    "kartik-v/yii2-widget-select2": "*",
    "linchpinstudios/yii2-filemanager": "dev-master",
    "kartik-v/yii2-widget-fileinput": "*",
    "php-ffmpeg/php-ffmpeg": "~0.5",
    "kartik-v/yii2-widget-datepicker": "*",
    "zendframework/zendsearch": "dev-master",
    "joni-jones/yii2-wschat": "dev-master"
},
"require-dev": {
    "yiisoft/yii2-codeception": "*",
    "yiisoft/yii2-debug": "*",
    "yiisoft/yii2-gii": "*",
    "yiisoft/yii2-faker": "*"
},
"config": {
    "process-timeout": 1800
},
"extra": {
    "asset-installer-paths": {
        "npm-asset-library": "vendor/npm",
        "bower-asset-library": "vendor/bower"
    }
}
```

}

**Comment by YevSent** [comment]
Seems, all packages are correct. Do you tried clear composer cache with `composer clear-cache`?

**Comment by QuinLena15** [comment]
I tried , to no avail. It may need some additional packages?

**Comment by YevSent** [comment]
No, all required packages are specified in requirements option. Right now I've tried to create new application with chat, all packages was loaded.
Please, write hash reference of `joni-jones/yii2-wschat` from `composer.lock` file.

**Comment by QuinLena15** [comment]
It is not in the file

**Comment by YevSent** [comment]
Sorry, not undersand your last comment.

**Comment by QuinLena15** [comment]
The file composer.lock no record joni-jones / yii2-wschat

**Comment by YevSent** [comment]
I need more time to investigate your problem.

**Comment by QuinLena15** [comment]
Thank you!

**Comment by YevSent** [comment]
I've tried different variants to install chat from composer. In all cases all packages was download successfully. Sorry, I can't reproduce your issue.

**Comment by QuinLena15** [comment]
Now a new error :
Could not load package cboden / ratchet in http://packagist.org: [UnexpectedValueException] Could not parse version constraint ^ 0.3: Invalid version string "^ 0.3"

**Comment by QuinLena15** [comment]
composer self-update. It helped me)

**Comment by YevSent** [comment]
Your problem is solved?

**Comment by QuinLena15** [comment]
yes
